# Generated by Django 5.2 on 2025-04-30 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('canal_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'canal_cliente',
                'ordering': ['canal_id'],
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('grupo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=5)),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'grupos_articulos',
                'ordering': ['codigo_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_identificacion', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('canal_id', models.ForeignKey(db_column='canal_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_canal', to='myapp.canalcliente')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['cliente_id'],
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('linea_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_linea', to='myapp.grupoarticulo')),
            ],
            options={
                'db_table': 'lineas_articulos',
                'ordering': ['codigo_linea'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('codigo_barras', models.CharField(max_length=250, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('presentacion', models.CharField(max_length=500, null=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_grupo', to='myapp.grupoarticulo')),
                ('linea', models.ForeignKey(db_column='linea_id', on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_linea', to='myapp.lineaarticulo')),
            ],
            options={
                'db_table': 'articulo',
                'ordering': ['articulo_id'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lista_articulo', to='myapp.articulo')),
            ],
            options={
                'db_table': 'lista_precio',
                'ordering': ['articulo_id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_pedido', to='myapp.cliente')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('articulo_id', models.ForeignKey(db_column='articulo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_articulo', to='myapp.articulo')),
                ('pedido_id', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_pedido', to='myapp.pedido')),
            ],
            options={
                'db_table': 'item_pedido',
                'ordering': ['item_id'],
            },
        ),
    ]
